version: "3.9"

services:
  web:
    build: .
    command: python run.py
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://microservice:microservice@db:5432/microservice
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: microservice
      POSTGRES_USER: microservice
      POSTGRES_PASSWORD: microservice
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
