apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Only rewrite Prometheus, keep Grafana sub-path intact
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      # Grafana — served from /grafana; $2 will preserve its suffix
      - path: /grafana(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: monitoring-grafana
            port:
              number: 80
      # Prometheus — served from /prometheus
      - path: /prometheus(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: monitoring-kube-prometheus-prometheus
            port:
              number: 9090
