global:
  rbac:
    create: true
  imagePullSecrets:
    - name: acr-pull-secret

grafana:
  adminPassword: changeme
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  ingress:
    enabled: false
  persistence:
    enabled: false

prometheus:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  prometheusSpec:
    retention: 15d
    scrapeInterval: 30s
    serviceMonitorSelectorNilUsesHelmValues: false

prometheusOperator:
  image:
    registry: microservicesdevw25mr.azurecr.io
    repository: monitoring/prometheus-operator
    tag: v0.75.2
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false

alertmanager:
  enabled: true
  service:
    type: ClusterIP
