global:
  rbac:
    create: true

grafana:
  adminPassword: changeme
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  ingress:
    enabled: false
  persistence:
    enabled: false

prometheus:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  prometheusSpec:
    retention: 15d
    scrapeInterval: 30s
    serviceMonitorSelectorNilUsesHelmValues: false

prometheusOperator:
  image:
    registry: mcr.microsoft.com
    repository: oss/prometheus-operator/prometheus-operator
    tag: v0.75.2
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  admissionWebhooks:
    patch:
      image:
        registry: mcr.microsoft.com
        repository: oss/kubernetes-ingress-controller/ingress-nginx/kube-webhook-certgen
        tag: v1.6.3
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists

alertmanager:
  enabled: true
  service:
    type: ClusterIP
