global:
  rbac:
    create: true
  imagePullSecrets:
    - name: acr-pull-secret

grafana:
  adminPassword: changeme
  replicaCount: 1
  image:
    registry: microservicesdevw25mr.azurecr.io
    repository: monitoring/grafana
    tag: 12.2.0
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  ingress:
    enabled: false
  persistence:
    enabled: false
  sidecar:
    dashboards:
      enabled: false
    datasources:
      enabled: false

prometheus:
  enabled: true
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  prometheusSpec:
    retention: 1d
    scrapeInterval: 30s
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi
    serviceMonitorSelectorNilUsesHelmValues: false
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists

prometheus-node-exporter:
  enabled: false

kubeStateMetrics:
  enabled: false

prometheusOperator:
  image:
    registry: microservicesdevw25mr.azurecr.io
    repository: monitoring/prometheus-operator
    tag: v0.86.1
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false

alertmanager:
  enabled: false
