apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservice-monitor
  namespace: microservice
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: microservice
      app.kubernetes.io/instance: microservice
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
