name: build-and-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: microservice

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Select Subscription
        run: az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push Docker image to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Ensure ACR admin enabled
        run: |
          az acr update --name ${{ secrets.ACR_NAME }} --admin-enabled true

      - name: Create monitoring pull secret
        run: |
          ACR_USER=$(az acr credential show --name ${{ secrets.ACR_NAME }} --query username -o tsv)
          ACR_PASS=$(az acr credential show --name ${{ secrets.ACR_NAME }} --query "passwords[0].value" -o tsv)
          kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
          kubectl create secret docker-registry acr-pull-secret \
            --namespace monitoring \
            --docker-server=${{ secrets.ACR_LOGIN_SERVER }} \
            --docker-username="$ACR_USER" \
            --docker-password="$ACR_PASS" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Import monitoring images into ACR
        run: |
          if ! az acr repository show --name ${{ secrets.ACR_NAME }} \
            --image monitoring/prometheus-operator:v0.75.2 >/dev/null 2>&1; then
            az acr import --name ${{ secrets.ACR_NAME }} \
              --source quay.io/prometheus-operator/prometheus-operator:v0.75.2 \
              --image monitoring/prometheus-operator:v0.75.2
          fi
          if ! az acr repository show --name ${{ secrets.ACR_NAME }} \
            --image monitoring/kube-webhook-certgen:v1.6.3 >/dev/null 2>&1; then
            az acr import --name ${{ secrets.ACR_NAME }} \
              --source registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.6.3 \
              --image monitoring/kube-webhook-certgen:v1.6.3
          fi

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Helm upgrade
        run: |
          helm upgrade --install ${{ env.IMAGE_NAME }} ./deploy/helm/microservice \
            --namespace ${{ secrets.AKS_NAMESPACE }} \
            --create-namespace \
            --set image.repository=${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }} \
            --set image.tag=${{ github.sha }}

      - name: Ensure monitoring stack
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
            --namespace monitoring \
            --create-namespace \
            -f deploy/monitoring/kube-prometheus-stack-values.yaml
